backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "images" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow

site_url: https://the-photographing-programmer.com/

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    delete: true
    slug: "{{title}}"
    preview_path: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Categories", name: "categories", widget: "list"}
      - label: "FeaturedImage"
        name: "featuredImage"
        widget: "object"
        required: false
        fields:
          - {label: "Src", name: "src", widget: "image"}
          - {label: "Alt", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - label: "Pages"
    name: "pages"
    files:
      - name: "About Page"
        label: "about"
        file: "content/About me.md"
        slug: "{{title}}"
        preview_path: "{{slug}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "FeaturedImage"
            name: "featuredImage"
            widget: "object"
            required: false
            fields:
              - {label: "Src", name: "src", widget: "image"}
              - {label: "Alt", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - name: "404 Page"
        label: "404"
        file: "content/404.md"
        slug: "{{title}}"
        preview_path: "{{slug}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "FeaturedImage"
            name: "featuredImage"
            widget: "object"
            required: false
            fields:
              - {label: "Src", name: "src", widget: "image"}
              - {label: "Alt", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
