---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: document
  path: content/pages/404.md
  label: '404'
- type: document
  path: content/pages/about-me.md
  label: About me
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
